"""Create RefactoringRecommendation model"""

# Generated by Django 3.2.15 on 2022-08-30 20:00

from django.conf import settings
from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):
    """Migration"""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefactoringRecommendation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    )
                ),
                (
                    'code',
                    models.TextField(
                        max_length=10000,
                        verbose_name='Исходный код',
                    )
                ),
                (
                    'recommendation',
                    models.TextField(
                        verbose_name='Рекомендация по рефакторингу',
                    )
                ),
                (
                    'date', models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Дата рефакторинга',
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    )
                ),
            ],
            options={
                'verbose_name': 'Рекомендация по рефакторингу',
                'verbose_name_plural': 'Рекомендации по рефакторингу',
                'ordering': ['-date'],
            },
        ),
    ]
