# Generated by Django 3.2.14 on 2022-07-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refactoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refactoringrecommendation',
            name='code',
            field=models.TextField(
                max_length=10000, verbose_name='исходный код'
            ),
        ),
        migrations.AlterField(
            model_name='refactoringrecommendation',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата рефакторинга'
            ),
        ),
        migrations.AlterField(
            model_name='refactoringrecommendation',
            name='recommendation',
            field=models.TextField(
                verbose_name='рекомендация по рефакторингу'
            ),
        ),
        migrations.AlterField(
            model_name='refactoringrecommendation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь'
            ),
        ),
    ]
