# Generated by Django 3.2.13 on 2022-06-11 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refactoring', '0002_userrecomendation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecomendation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrecomendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
