# Generated by Django 3.2.13 on 2022-06-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refactoring', '0003_auto_20220611_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecomendation',
            options={'ordering': ['-date'], 'verbose_name': 'Рекомендации по рефакторингу'},
        ),
    ]
