# Generated by Django 3.2.13 on 2022-06-19 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refactoring', '0004_alter_userrecomendation_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRecomendation',
            new_name='RefactoringRecommendation',
        ),
        migrations.AlterModelOptions(
            name='refactoringrecommendation',
            options={'ordering': ['-date'], 'verbose_name': 'Рекомендация по рефакторингу', 'verbose_name_plural': 'Рекомендации по рефакторингу'},
        ),
    ]
