# Generated by Django 3.2.13 on 2022-06-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refactoring', '0005_auto_20220619_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refactoringrecommendation',
            old_name='recomendation',
            new_name='recommendation',
        ),
    ]
